# Generated by Django 3.1 on 2020-08-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200816_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='symbol',
            field=models.ImageField(blank=True, height_field=150, upload_to='symbols/', width_field=150),
        ),
    ]
