# Generated by Django 3.1 on 2020-08-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200816_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='symbol',
            field=models.ImageField(blank=True, upload_to='symbols/'),
        ),
    ]
