# Generated by Django 3.1 on 2020-09-02 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_auto_20200822_1907'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='blog_comment',
        ),
        migrations.AlterModelTable(
            name='postimage',
            table='blog_postimage',
        ),
        migrations.CreateModel(
            name='BookMarkPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'bookmark_post',
            },
        ),
    ]
