# Generated by Django 3.1 on 2020-09-04 06:01

from django.conf import settings
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0016_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favorite',
        ),
        migrations.AddField(
            model_name='post',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
