# Generated by Django 3.1 on 2020-09-05 19:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200905_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
