# Generated by Django 3.1 on 2020-09-02 20:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.CharField(blank=True, max_length=225, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=50, verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterModelTable(
            name='contactmessage',
            table='home_contactmessage',
        ),
        migrations.AlterModelTable(
            name='faq',
            table='home_faq',
        ),
    ]
