# Generated by Django 3.0.8 on 2020-07-29 23:10

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200728_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=746, multiple=True, verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Null', upload_to='images/', verbose_name='图片'),
        ),
    ]
