# Generated by Django 3.0.8 on 2020-07-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200730_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': '博客图片', 'verbose_name_plural': '博客图片'},
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='上传图片'),
        ),
        migrations.AlterModelTable(
            name='postimage',
            table='blog_postimage',
        ),
    ]
